# ใช้ Node.js เวอร์ชัน 22
FROM node:22

# ตั้ง working directory
WORKDIR /usr/src/app

# ติดตั้ง dependencies ก่อน เพื่อ cache
COPY package*.json ./
RUN npm install

# คัดลอก source code ทั้งหมด
COPY . .

# เปิด port 3000
EXPOSE 3000

# รัน NestJS แบบ hot reload
CMD ["npm", "run", "start:dev"]
